name: catbreeds
description: An app to discover the breed of your cat
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  catbreed_api_client:
    path: packages/catbreed_api_client
  catbreed_repository:
    path: packages/catbreed_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.3
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  logging: ^1.2.0
  url_launcher: ^6.3.0
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
