name: app_domain
description: App domain models
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.16.0
  very_good_analysis: ^5.1.0
